spring:
  config:
    import: zookeeper:127.0.0.1:2181
  application:
    name: cloud-client2
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  data:
  redis:
    host: 127.0.0.1
    password:
    port: 6379

server:
  port: 8092
logging:
  level:
    root: info


